import streamlit as st
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
from src.inference import InferenceEngine

# =============================================================================
# STREAMLIT INTERFACE
# =============================================================================
# Phase 7: Deployment
# This is the frontend for the Financial Forecasting Model.
# =============================================================================

st.set_page_config(page_title="Hybrid Financial Forecaster", layout="wide")

# Title and Header
st.title("📈 LSTM-Transformer Hybrid Forecaster")
st.markdown("""
This application uses a hybrid Deep Learning model (LSTM + Transformer) to forecast the 
**direction** of the S&P 500 (or other assets) for the next trading day.
""")

# Sidebar settings
st.sidebar.header("Configuration")
ticker = st.sidebar.text_input("Ticker Symbol", value="^GSPC")
st.sidebar.caption("Default: S&P 500 (^GSPC)")

if st.sidebar.button("Run Forecast"):
    with st.spinner(f"Fetching data and calculating predictions for {ticker}..."):
        try:
            # Initialize Engine
            engine = InferenceEngine(scaler_path="scaler.save")
            
            # Predict
            result = engine.predict_next_day(ticker)
            
            # Display Metrics
            col1, col2, col3, col4 = st.columns(4)
            
            with col1:
                st.metric("Latest Date", result['last_date'].strftime('%Y-%m-%d'))
            
            with col2:
                direction = result['direction']
                color = "normal"
                delta_color = "off"
                if direction == "UP":
                    delta_color = "normal" # Green usually
                else:
                    delta_color = "inverse" # Red usually
                
                st.metric("Prediction", direction, delta=f"{result['prediction_log_return']:.4f}", delta_color=delta_color)

            with col3:
                 st.metric("Log Return", f"{result['prediction_log_return']:.5f}")

            with col4:
                 st.metric("Model Confidence (Abs Scaled)", f"{result['confidence']:.4f}")

            # Visualization
            st.subheader("Recent Market Context (Last 100 Days)")
            
            # Fetch data again just for plotting (Engine fetches internally but doesn't return full DF)
            # Efficient way: The engine could return a small df, but for now we re-fetch lightly.
            chart_data = yf.download(ticker, period="100d", auto_adjust=True, progress=False)
            if isinstance(chart_data.columns, pd.MultiIndex):
                chart_data.columns = chart_data.columns.get_level_values(0)

            fig = go.Figure(data=[go.Candlestick(x=chart_data.index,
                            open=chart_data['Open'],
                            high=chart_data['High'],
                            low=chart_data['Low'],
                            close=chart_data['Close'])])
            
            fig.update_layout(title=f"{ticker} Recent Price Action", yaxis_title="Price")
            st.plotly_chart(fig, use_container_width=True)
            
        except Exception as e:
            st.error(f"Error during forecasting: {e}")

st.divider()
st.caption("⚠️ Disclaimer: This tool is for educational purposes only. The predictions are generated by an experimental AI model and should not be used as financial advice.")
